# LVM
root_lv_path: "/dev/mapper/fedora-root"          # change if your LV name differs
# GRUB kernel parameters (4GB RAM + 124 GPU VRAM settings)
extra_grub_params: >-
  amd_iommu=off amdgpu.gttsize=126976 ttm.pages_limit=32505856
grub_defaults_file: "/etc/default/grub"
grub_cfg_path:      "/boot/grub2/grub.cfg"

# Fedora version (for firmware downgrade)
fedora_version: "43"
#broken_firmware_version: "20251125"
#safe_firmware_version: "20251111"

# Packages to install
base_packages:
  - toolbox
  - python3-pip
  - vim
  - curl
  - git

# Repository with the toolboxes
toolbox_repo_url: "https://github.com/kyuz0/amd-strix-halo-toolboxes"
toolbox_repo_dest: "{{ ansible_user_dir }}/amd-strix-halo-toolboxes"

# Toolbox definitions (ROCM & VULKAN)
toolboxes:
  - name: "llama-rocm-7.2"
    image: "docker.io/kyuz0/amd-strix-halo-toolboxes:rocm-7.2"
    extra_opts: >-
      --device /dev/dri --device /dev/kfd
      --group-add video --group-add render --group-add sudo
      --security-opt seccomp=unconfined

  - name: "llama-rocm7-nightlies"
    image: "docker.io/kyuz0/amd-strix-halo-toolboxes:rocm7-nightlies"
    extra_opts: >-
      --device /dev/dri --device /dev/kfd
      --group-add video --group-add render --group-add sudo
      --security-opt seccomp=unconfined

  - name: "llama-vulkan-radv"
    image: "docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv"
    extra_opts: >-
      --device /dev/dri
      --group-add video --security-opt seccomp=unconfined

# Model files to download
model_dir: "{{ ansible_user_dir }}/models"
model_urls:
  # GPT OSS
  - "https://huggingface.co/unsloth/gpt-oss-120b-GGUF/resolve/main/UD-Q8_K_XL/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf"
  - "https://huggingface.co/unsloth/gpt-oss-120b-GGUF/resolve/main/UD-Q8_K_XL/gpt-oss-120b-UD-Q8_K_XL-00002-of-00002.gguf"
  # Qwen Coder Next
  - "https://huggingface.co/bartowski/Qwen_Qwen3-Coder-Next-GGUF/resolve/main/Qwen_Qwen3-Coder-Next-Q8_0/Qwen_Qwen3-Coder-Next-Q8_0-00001-of-00003.gguf"
  - "https://huggingface.co/bartowski/Qwen_Qwen3-Coder-Next-GGUF/resolve/main/Qwen_Qwen3-Coder-Next-Q8_0/Qwen_Qwen3-Coder-Next-Q8_0-00002-of-00003.gguf"
  - "https://huggingface.co/bartowski/Qwen_Qwen3-Coder-Next-GGUF/resolve/main/Qwen_Qwen3-Coder-Next-Q8_0/Qwen_Qwen3-Coder-Next-Q8_0-00003-of-00003.gguf"
  # Qwen 3.5
  - "https://huggingface.co/bartowski/Qwen_Qwen3.5-122B-A10B-GGUF/resolve/main/Qwen_Qwen3.5-122B-A10B-Q6_K_L/Qwen_Qwen3.5-122B-A10B-Q6_K_L-00001-of-00003.gguf"
  - "https://huggingface.co/bartowski/Qwen_Qwen3.5-122B-A10B-GGUF/resolve/main/Qwen_Qwen3.5-122B-A10B-Q6_K_L/Qwen_Qwen3.5-122B-A10B-Q6_K_L-00002-of-00003.gguf"
  - "https://huggingface.co/bartowski/Qwen_Qwen3.5-122B-A10B-GGUF/resolve/main/Qwen_Qwen3.5-122B-A10B-Q6_K_L/Qwen_Qwen3.5-122B-A10B-Q6_K_L-00003-of-00003.gguf"
  - "https://huggingface.co/bartowski/Qwen_Qwen3.5-122B-A10B-GGUF/resolve/main/mmproj-Qwen_Qwen3.5-122B-A10B-f16.gguf" # mmproj file for visual inputs

llama_swap_releases_url: "https://api.github.com/repos/mostlygeek/llama-swap/releases/latest"
llama_swap_path: "{{ ansible_user_dir }}/llama-swap"

user_systemd_dir: "{{ ansible_user_dir }}/.config/systemd/user"
